### ISSUE TITLE
Incorrect C++ generated code

### ISSUE THREAD

**Issue by sletz** [paolomarrone/Zampogna#2]
The following line `static const float decibel_range_1 = 40.f;` appears twice in https://github.com/paolomarrone/Zampogna/blob/main/test/EQregalia/build/vst2_EQregalia.cpp#L4

**Comment by paolomarrone** [comment]
Thanks for the report.
I just updated a new version of Zampogna which contains the developments of the last months. That kind of bugs and others are all resolved there.
